import { Nunito } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <link
        rel="icon"
        href="file:///Users/bikramgarg/Desktop/Screenshot%202024-05-05%20at%2010.24.28%20PM.png"
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
